# Use this environment file if your computer has a nvidia GPU and runs Windows or Linux.

name: llava-training

channels:
    - nvidia
    - conda-forge
    - anaconda

dependencies:
  - nvidia::cuda-toolkit
  - nvidia::cuda-compiler
  - conda-forge::ninja
  - conda-forge::deepspeed
