# Use this environment file if your computer has a nvidia GPU and runs Windows or Linux.

name: llava

channels:
    - pytorch
    - nvidia
    - conda-forge
    - anaconda

dependencies:
  - python~=3.12
  - pip
  - pytorch::pytorch-cuda~=12.1
  - pytorch::pytorch=*=*cuda12.1* # | linux-64/pytorch-2.3.0-py3.12_cuda12.1_cudnn8.9.2_0.tar.bz2
  - pytorch::torchvision
  - numpy
  - scikit-learn>=1.2.2
  - accelerate>=0.21.0
  - bitsandbytes
  - einops>=0.6.1
  - fastapi
  - gradio>=4.16.0
  - gradio-client>=0.8.1
  - httpx>=0.24.0
  - markdown2
  - peft
  - pip
  - protobuf
  - pydantic
  - requests
  - sentencepiece>=0.1.99
  - shortuuid
  - timm>=0.6.13
  - tokenizers>=0.15.1
  - transformers>=4.37.2
  - uvicorn
  - pip:
    - einops-exts>=0.0.4

    # Anything else that pip requirement files allows should work seamlessly...
#  - nvidia/label/cuda-12.4.1::cuda-toolkit
#  - nvidia/label/cuda-12.4.1::cuda-nvcc 
#  - anaconda::cudnn
#  - deepspeed
#  - ninja
