name: Apptainer Build
on:
  push:
    tags:
      - "*@*"
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    name: Build Apptainer image
    permissions:
        contents: read
        packages: write
    steps:
      - name: Download Apptainer
        run: |
          set -eux
          APPTAINER_VERSION="${APPTAINER_VERSION:-1.2.5}"
          curl -o "apptainer-${APPTAINER_VERSION}.deb" -L https://github.com/apptainer/apptainer/releases/download/v${APPTAINER_VERSION}/apptainer_${APPTAINER_VERSION}_amd64.deb
          export DEBIAN_FRONTEND=noninteractive
          { sudo apt-get update -yq && sudo apt-get upgrade -yq; } || echo "Couldn't update apt packages. Will attempt installation without update & upgrade." >&2
           sudo dpkg --install --force-depends "apptainer-${APPTAINER_VERSION}.deb" && sudo apt-get install --fix-broken --yes --quiet
           apptainer >&2 --version && echo >&2 "Apptainer installed successfully!"
      - name: Install ORAS
        run: |
          set -eux
          ORAS_VERSION="${ORAS_VERSION:-1.1.0}"          
          curl -o "oras_${ORAS_VERSION}.tar.gz" -L "https://github.com/oras-project/oras/releases/download/v${ORAS_VERSION}/oras_${ORAS_VERSION}_linux_amd64.tar.gz"

          # Install the executable:
          tar -xvf oras_${ORAS_VERSION}.tar.gz && chmod +x oras && sudo mv oras /usr/local/bin/oras
          sudo mv "${DOWNLOAD_PATH}" /usr/local/bin/oras && sudo chmod +x /usr/local/bin/oras & oras >&2 version && echo >&2 "oras installed successfully!"
      - name: Check out code for the container build
        uses: actions/checkout@v4
      - name: Build Container
        run: |
          set -eux
          IMAGE_PATH="$(basename ${PWD})".sif
          apptainer build --disable-cache --fix-perms --force "${IMAGE_PATH}" Singularity
          echo "Container built successfully" >&2
          echo "Container size:" >&2
          du -h "${IMAGE_PATH}" >&2
          echo "Container labels:" >&2
          apptainer inspect "${IMAGE_PATH}" >&2
          echo "export IMAGE_PATH=\"${IMAGE_PATH}\"" >> $GITHUB_ENV
      - name: Push Container
        run: |
          set -eux
          IMAGE_TAG=${{ github.ref_name }}
          IMAGE_TAG=${IMAGE_TAG:-latest}
          IMAGE_TAG="${IMAGE_TAG##*@}"
          IMAGE_NAME=${{ github.ref_name }}
          IMAGE_NAME="${IMAGE_NAME%%@*}"
          apptainer remote login -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}  oras://ghcr.io/${{ github.repository }}
          apptainer push -U "${IMAGE_PATH}" oras://ghcr.io/${{ github.repository }}/${IMAGE_NAME}:${IMAGE_TAG}
          if [[ "${IMAGE_TAG}" != "latest" ]]; 
            oras login -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }} ghcr.io
            oras tag ghcr.io/${{ github.repository }}/${IMAGE_NAME}:${IMAGE_TAG} latest
          fi
          echo "Done" >&2
